version: '2'

services:
    frontend:
        # image: 'ignema/bricoly-frontend'
        build: 
            context: ./senna_front/
        ports: 
            - 3000:3000
        container_name: senna_front
    backend:
        # image: 'ignema/bricoly-backend'
        build:
            context: ./senna_backend/
        ports: 
            - 8080:8080
        container_name: senna_backend
        sysctls:

            net.core.somaxconn: 512
            kernel.shmmax:  18102030100020003000
            kernel.msgmax:  4000
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/senna
            - SPRING_DATASOURCE_USERNAME=senna
            # Make sure to change this in prod!!
            - SPRING_DATASOURCE_PASSWORD=12345
            - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop # Needs to be set to 'update' in prod
            ###################################
          
    db:
        image: 'postgres:13.1-alpine'
        container_name: senna_db
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=senna
            # Make sure to change this in prod!!
            - POSTGRES_PASSWORD=12345
            ###################################